### PR TITLE
Support vector<obx_id> in in/notIn query filters and setParameter

### LINKED ISSUE #42: in filter does not support obx_id
**Describe the bug**
Cannot use in filter with obx_id

**Basic info (please complete the following information):**
 - ObjectBox version: 4.0.0
 - C++ version: 17
 - Reproducibility:  always
 - OS: Ubuntu 22.04

**To Reproduce**
1. Create vector of obx_id
2. Pass vector to "in" filter
3. Compiler error

**Expected behavior**
Should be able to handle obx_id

**Code**

```
database.fbs - example
table Device {
    /// objectbox:id
    id                        : ulong;
    active                    : bool; 
} 
```
```
std::vector<obx_id> requestIDs = {1, 2, 9};
tableDevice_.query().with(Device_::id.in(requestIDs)).build().findUniquePtrs(); // Fails to compile

std::vector<int64_t> requestIDs = {1, 2, 9};
tableDevice_.query().with(Device_::id.in(requestIDs)).build().findUniquePtrs(); // Is ok
```
This is caused as the template implementation for uint64_t is missing and obx_id is unsigned 64bit
```
objectbox.h
typedef uint64_t obx_id;
```
For our system we do not have big obx_id values bigger than 9,223,372,036,854,775,807 but a unsigned/signed conversion must be made or implement our own template in objectbox.hpp

### PR DESCRIPTION
**Pull request by Tyagiquamar**
Fixes #42.

obx_id is uint64_t (objectbox.h) but Property in/notIn only accepted vector<int32_t>/vector<int64_t>, so passing vector<obx_id> failed to compile.

This adds header-only vector<obx_id> overloads for in/notIn (Long/Relation properties) and a Query setParameter overload, each converting to the existing int64 path with a same-size static_assert.

Compile-checked: g++ 12 -std=c++17 -fsyntax-only on include/objectbox.hpp plus a TU instantiating in(ids)/notIn(ids) with vector<obx_id> (lvalue and rvalue) - both clean.

### CODE REVIEW

**Comment by Tyagiquamar** [comment]
Independent verification of the fails-before case (g++ 12, -std=c++17, header-only TU instantiating in/notIn with vector<obx_id> lvalue and rvalue): pre-fix header fails with the exact error from #42 (no matching function for call to in(std::vector<long unsigned int>&)); post-fix header compiles with exit 0 and no warnings under -Wall.
